### ISSUE TITLE
Implement company role

### ISSUE THREAD

**Issue by motero2k** [Miguel-Angel-Roldan-Garcia/Acme-L3#32]
4)	There is a new project-specific role called **company**, which has the following profile data: 

- [ ] **name** (not blank, shorter than 76 characters), 
- [ ] **VAT** number (not blank, shorter than 26 characters), 
- [ ] **summary** (not blank, shorter than 101 characters), 
- [ ] an optional **link** with further information.

**Comment by JaviFdez7** [comment]
Beginning of the company role creation task

**Comment by JaviFdez7** [comment]
Task finished and commit done. There is now a role called company with the described attributes

**Comment by JaviFdez7** [comment]
Task finished and commit done. There is now a role called company with the described attributes
