### ISSUE TITLE
Implement practicum

### ISSUE THREAD

**Issue by motero2k** [Miguel-Angel-Roldan-Garcia/Acme-L3#33]
5)	[MANDATORY] A **practicum** helps put hands-on courses into practice in the context of a real company.  The system must store the following data about them: 

- [x] a **code** (pattern “[A-Z]{1,3}[0-9][0-9]{3}”, not blank, unique), 
- [x] a **title** (not blank, shorter than 76 characters),
- [x]  an **abstract** (not blank, shorter than 101 characters),
- [x]  some **goals** (not blank, shorter than 101 characters), 
- [x] an **estimated total time** (in hours, computed from the corresponding sessions plus/minus 10%).

**Comment by JaviFdez7** [comment]
Documento de análisis
https://ev.us.es/ultra/courses/_63009_1/cl/outline

**Comment by JaviFdez7** [comment]
Requisito con incorrección:
https://ev.us.es/webapps/discussionboard/do/message?action=list_messages&course_id=_63009_1&nav=discussion_board&conf_id=_303964_1&forum_id=_206215_1&message_id=_357834_1
