### ISSUE TITLE
Implement Sessions

### ISSUE THREAD

**Issue by motero2k** [Miguel-Angel-Roldan-Garcia/Acme-L3#34]
6)	[MANDATORY] The system must store the following data about the **sessions** in a practicum: 

- [x] a **title** (not blank, shorter than 76 characters),
- [x]  an **abstract** (not blank, shorter than 101 characters), 
- [x] a time **period** (at least one week ahead, at least one week long), 
- [x] an optional **link** with further information.

**Comment by JaviFdez7** [comment]
Análisis relizado en el documento de análisis
