### ISSUE TITLE
Company dashboards

### ISSUE THREAD

**Issue by motero2k** [Miguel-Angel-Roldan-Garcia/Acme-L3#35]
7)	The system must handle **company dashboards** with the following data: 

- [x] total **number** of practica regarding **theory or hands-on** courses grouped by month during the last year; 
- [x] average, deviation, minimum, and maximum period length of the **sessions** in their practica; 
- [x] average, deviation, minimum, and maximum period length of their **practica**.

**Comment by JaviFdez7** [comment]
https://ev.us.es/ultra/courses/_63009_1/cl/outline

**Comment by JaviFdez7** [comment]
Contradicción en el requisito 7:
https://ev.us.es/webapps/discussionboard/do/message?action=list_messages&course_id=_63009_1&nav=discussion_board&conf_id=_303964_1&forum_id=_206215_1&message_id=_358417_1

**Comment by JaviFdez7** [comment]
Contradicción añadida en el documento de análisis
