### ISSUE TITLE
Implement Offer entity

### ISSUE THREAD

**Issue by motero2k** [Miguel-Angel-Roldan-Garcia/Acme-L3#6]
12)	[MANDATORY] An offer is a record in which an administrator advertises something.  The system must store the following data about them: 

- [x] an **instantiation** moment (in the past), 
- [x] a **heading** (not blank, shorter than 76 characters), 
- [x] a **summary** (not blank, shorter than 101 characters), 
- [x] an **availability** period (at least one day after the offer is instantiated and must last for at least one week), 
- [x] a **price** (positive, possibly nought), 
- [x] an optional **link** with further information.

**Comment by JaviFdez7** [comment]
Terminada
